<script type="text/javascript">
//<![CDATA[
new ShipperHQ.JQueryLoader(
    {
        "jquery": { "default": "1.11.2" },
        "ui": {
            "default": "1.11.2", // By default all use new version
            "1.5": "1.8.24",
            "1.4": "1.8.24",
            "1.3": "1.8.24"
        }
    },
    {
        "jquery": "//ajax.googleapis.com/ajax/libs/jquery/{version}/jquery.min.js",
        "ui": "//ajax.googleapis.com/ajax/libs/jqueryui/{version}/jquery-ui.min.js",
        "ui-style": "//ajax.googleapis.com/ajax/libs/jqueryui/{version}/themes/ui-lightness/jquery-ui.css"
    }
);   
//]]>
</script> 