<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    $gallery = '<div class="more-views"><a class="prev"><img src="https://www.oaktreegardencentre.com/skin/frontend/default/sanorita/images/up-arrow.gif" alt="Next" /></a>';
    $gallery .= '<ul>';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(95) . '"  alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a><span class="hidden-desktop">' . $this->htmlEscape($_image->getLabel()) . '</span>'
                 .  '</li>';
    }
    $gallery .= '</ul><a class="next"><img src="https://www.oaktreegardencentre.com/skin/frontend/default/sanorita/images/down-arrow.gif" alt="Next" /></a></div>';
}
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="badge">
	<?php if($_product->getData('new')){echo '<span class="new">'. $_product->getAttributeText('new').'</span>';  }?>
    <?php if($_product->getData('sale')){echo '<span class="sale">'. $_product->getAttributeText('sale').'</span>';  }?>
    </div>
<div class="amlabel-div">
<?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
<p class="product-image product-image-zoom">
	
    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom ajax" id="cloudZoom">
    <?php
        $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a>
</p>
</div>
    <?php if(isset($gallery)): ?>
        <p class="zoom-notice" id="track_hint"><?php echo $this->__('Click on above image to view full picture') ?></p>
       <div class="thumbbox"><?php echo $gallery; ?></div>
    <?php endif; ?>
<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
<script type="text/javascript">
	jQuery(document).ready(function(){
		var trigggerflag = 1;
		jQuery('.product-image-zoom #wrap').click(function(){
			if(trigggerflag){
			   trigggerflag =0;
			   jQuery('#cloudZoom').trigger('click');
			} 
			trigggerflag =1;		
	});
	});
</script>

