<div class="banner-main">
        <ul class="rslides" id="bannerslides">
        	<?php $banner_model = new Juno_Banners_Model_Image(); ?>
            <?php $banners = Mage::getResourceModel('banners/image_collection')->addFieldToFilter('status',1)->addImageCodeFilter('home_banner')->setOrderByPosition(); ?>
            <?php if(count($banners)>=1) {?>
				<?php foreach($banners as $banner) { ?>
                    <?php $banner = $banner_model->load($banner['image_id']); ?>
                    <?php if( $banner->getStatus() == 1 ) { ?>
                        <?php $url = $banner->getUrl();?>
                        <?php if($url) {?>
                            <li>
                                <a href="<?php echo $url; ?>"><img src="<?php echo $banner->getImageUrl();?>" <?php if(count($banners)===1){?> style="padding-bottom:10px;"<?php }?> alt="<?php echo $banner['title'];?>"/></a>
                            </li>
                        <?php }else{ ?>
                            <li>
                                <img src="<?php echo $banner->getImageUrl();?>" <?php if(count($banners)===1){?> style="padding-bottom:10px;"<?php }?> alt="<?php echo $banner['title'];?>"/>
                            </li>
                        <?php }?>   
                    <?php } ?>
                <?php }?>
            <?php } else{ ?>
            	<li>
            		<a href="#"><img src="<?php echo $this->getSkinUrl('images/banner-home_1.jpg') ?>" style="padding-bottom:10px;" alt="" /></a>
                </li>
            <?php } ?>
        </ul>
    </div>
